#!/bin/sh

set -e
. $(dirname "$0")/common

cd "$DIR_BUILD"

distcheck()
{
  if make -j${NBPROC:-2} vcsn-distcheck "$@" </dev/null; then
    :
  else
    sta=$?
    # If distcheck was run and failed in its course, it probably
    # left readonly directories that Teamcity will fail to clean.
    #
    for distdir in vcsn-*
    do
      if test -d "$distdir"; then
        # Taken from Automake's am__remove_distdir.
        find "$distdir" -type d ! -perm -200 -exec chmod u+w {} ';'
      fi
    done
    exit $sta
  fi
}

distcheck DISTCHECK_CONFIGURE_FLAGS='CPPFLAGS="$(CPPFLAGS)" CXX="$(CXX)" CXXFLAGS="$(CXXFLAGS)" LDFLAGS="$(LDFLAGS)"'
