#!/bin/sh

set -e
. $(dirname "$0")/common

compute_package_id

cd "$DIR_BUILD"

rm -rf $DIR_INSTALL $PACKAGE_ID.install
make install DESTDIR=$DIR_INSTALL
mv $DIR_INSTALL/usr/local $PACKAGE_ID.install
tar jcf $PACKAGE_ID.binary.tar.bz2 $PACKAGE_ID.install
