#!/bin/sh

set -e
. $(dirname "$0")/common

compute_package_id

cd "$DIR_BUILD"

# Build the docker package.
cp "$DIR_SOURCE/Dockerfile" .
cp "$DIR_SOURCE/debuild/sources.list" .
docker build -t lrde/vcsn .

# Save it locally, to provide it as an artifact for instance.
docker save lrde/vcsn | gzip > vcsn-docker-image.tar.gz

# Then push it to DockerHub.
docker push lrde/vcsn
