#!/bin/sh

# Build the Docker image using the Debian package.  Does not need a
# configured tree.  It doesn't even have to be bootstrapped.

set -e
. $(dirname "$0")/common

cd "$DIR_BUILD"

# Build the Docker image.
cp "$DIR_SOURCE/Dockerfile" .
cp "$DIR_SOURCE/debuild/sources.list" .

# --no-cache because otherwise we download the images once (e.g.,
# --Debian Sid) and keep using them, never updating them.
docker build --no-cache -t lrde/vcsn .

# Save it locally, to provide it as an artifact for instance.
docker save lrde/vcsn | gzip > vcsn-docker-image.tar.gz

# Then push it to DockerHub.
docker push lrde/vcsn
