((nil . ((whitespace-action auto-cleanup)
         (whitespace-style empty tabs trailing lines-tail)
         (require-final-newline . t)
         (mode . whitespace)
         ))
 (c++-mode . ((c-default-style . "gnu")
              (indent-tab-mode . nil)
              (fill-column . 70))))
