.vcsn_template: &vcsn_template
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - /root/.ccache
  script:
    - pwd
    - ccache -s
    - ccache -M 20GB
    - ccache -s
    - ./bootstrap
    - mkdir build
    - cd build
    - ../configure CPPFLAGS="$CPPFLAGS" CC="$CC" CXX="$CXX" CXXFLAGS="$CXXFLAGS"
    - make
    - if [[ $CHECK == "installcheck" ]]; then make install; fi
    - make "$CHECK"
    - ccache -s
  artifacts:
    when: always
    paths:
      - build/*.log
      - build/*/*.log
      - build/*/*/*.log

archlinux:gcc:speed:
  <<: *vcsn_template
  image: registry.lrde.epita.fr/vcsn-build-arch
  variables:
    CPPFLAGS: -DNDEBUG
    CC: gcc
    CXX: g++
    CXXFLAGS: -O3
    CHECK: check

archlinux:clang:debug:
  <<: *vcsn_template
  image: registry.lrde.epita.fr/vcsn-build-arch
  variables:
    CC: clang
    CXX: clang++
    CHECK: installcheck

debian:gcc:debug:
  <<: *vcsn_template
  image: registry.lrde.epita.fr/vcsn-build-debian
  variables:
    CC: gcc
    CXX: g++
    CHECK: check

debian:clang:speed:
  <<: *vcsn_template
  image: registry.lrde.epita.fr/vcsn-build-debian
  variables:
    CPPFLAGS: -DNDEBUG
    CC: clang
    CXX: clang++
    CXXFLAGS: -O3
    CHECK: installcheck
