# -*- mode: ruby -*-

# Vagrantfile API/syntax version. Don't touch unless you know what
# you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "vcsn"
  config.vm.box_url = "vcsn.box"

  config.vm.network :forwarded_port, guest: 8888, host: 8888
end
