#! /bin/sh

set -e

me=`basename $1 .chk`

# Number of the current test.
number=1

# Exit status of this script.
exit=true

# Make them absolute.
builddir=$(pwd)
srcdir=$(cd $srcdir && pwd)
test=$(cd $(dirname $1) && pwd)/$(basename $1)


# stderr LINES
# ------------
stderr ()
{
  local i
  for i
  do
    echo "$i"
  done | sed -e "s/^/$me: /" >&2
}


# error EXIT MESSAGES
# -------------------
error ()
{
  local exit="$1"
  shift
  stderr "$@"
  exit $exit
}


# fatal MESSAGES
# --------------
fatal ()
{
  error 1 "$@"
}


# rst_title TITLE
# ---------------
rst_title ()
{
  echo "$@" | sed 's/.*/   &   /;h;s/./=/g;p;x;p;g;p;s/.*//'
}

# rst_section_ LINER TITLE
# ------------------------
rst_section_ ()
{
  local liner="$1"
  shift
  echo "$@" | sed "p;s/./$liner/g;p;g"
  echo
}

# rst_section TITLE
# -----------------
rst_section ()
{
  rst_section_ "=" "$@"
}

# rst_subsection TITLE
# --------------------
rst_subsection ()
{
  rst_section_ "-" "$@"
}

# rst_subsubsection TITLE
# -----------------------
rst_subsubsection ()
{
  rst_section_ "." "$@"
}

# rst_tab [FILES = stdin]
# -----------------------
rst_tab ()
{
  # We use "cat -v" so that we don't miss hidden characters, but
  # also so Windows runs don't display with an empty line between
  # one line.  They now display as "LINE^M".
  cat -v "$@" | perl -pe 's/\^\[\[33/\x1B\[33/g;s/^/\t/'
  echo
}

# rst_pre TITLE [FILE]
# --------------------
# FILE may be empty to denote stdin.
rst_pre ()
{
  if test $# -eq 1 || test -s "$2"; then
    echo "$1::"
    echo
    shift
    rst_tab "$@"
  fi
}


# rst_expect BASE [DIFF-FLAGS]
# ----------------------------
# Compare expected output with effective, actual, output.
# Set $exit to false if there is a failure.
rst_expect ()
{
  local base=$1
  shift
  rst_subsubsection "$me: $base"
  # Dump something, it is really surprising in the logs to see
  # nothing.
  rst_pre "Expected $base for $me"      $base.exp

  test -f $base.exp ||
    fatal "missing reference file: $base.exp"

  # --strip-trailing-cr helps to fight \r.
  if ! diff --strip-trailing-cr -u                              \
            --label="Expected $base ($base.exp)"  $base.exp     \
            --label="Effective $base ($base.eff)" $base.eff     \
            "$@"                                                \
            >$base.diff; then
    rst_pre "Effective $base for $me"   $base.eff
    rst_pre "Diffs on $base for $me"    $base.diff
    # If exit is already set, e.g. to "exit SKIP", don't alter it.
    case $exit in
      ('' | true) exit=false;;
    esac
  fi
}


# run EXPECTED-EXIT-STATUS EXPECTED-OUTPUT [SUCS-OPTIONS]
# -------------------------------------------------------
run ()
{
  # Expected exit status.
  local sta_exp=$1
  shift
  # Expected output.
  local out_exp=$1
  shift
  if test "$out_exp" != out.exp; then
    cat >out.exp <<EOF
$out_exp
EOF
  fi
  # Effective exit status, output and error.
  local sta_eff=0
  # Be robust to set -e.
  rst_subsubsection $number
  $builddir/$prog "$@" >out.eff 2>err.eff || sta_eff=$?
  if test $sta_eff -ne $sta_exp; then
    echo "$me: FAIL: $number (expected status: $sta_exp, effective: $sta_eff)"
    exit=false
  fi
  rst_expect out
  rst_pre "Standard error" err.eff
  cat <<EOF

test $number:
	sucs $@
status: $sta_eff
EOF
  number=`expr $number + 1`
}

# cleanup
# -------
cleanup ()
{
  local status=$?
  if test -z "$DEBUG"; then
     cd $builddir
     rm -rf $me.dir
  fi
  exit $status
}
trap cleanup 0 1 2 13 15
rm -rf $me.dir
mkdir $me.dir
cd $me.dir

. "$test"

$exit
