## Vaucanson 2, a generic library for finite state machines.
## Copyright (C) 2012-2016 Vaucanson Group.
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## The complete GNU General Public Licence Notice can be found as the
## `COPYING' file in the root directory.
##
## The Vaucanson Group consists of people listed in the `AUTHORS' file.

dist_pkglibexec_SCRIPTS =                       \
  %D%/vcsn-compile                              \
  %D%/vcsn-gdb                                  \
  %D%/vcsn-notebook                             \
  %D%/vcsn-ps                                   \
  %D%/vcsn-score                                \
  %D%/vcsn-score-compare


# The generator.
tafkit_gen = build-aux/bin/tafkit-gen
dist_noinst_python += $(tafkit_gen)
# Files generated by tafkit_gen.
from_tafkit_gen =	\
	%D%/vcsn-tafkit-algos.cc
CLEANFILES += %D%/tafkit.stamp $(from_tafkit_gen)
%D%/tafkit.stamp: $(tafkit_gen) vcsn/dyn/algos.json
	$(AM_V_GEN)$(mkdir_p) $(@D)
	$(AM_V_at)rm -f $@ $@.tmp
	$(AM_V_at)echo '$@ rebuilt because of: $?' >$@.tmp
	$(AM_V_at)$(PYTHON) $(srcdir)/$(tafkit_gen)                     \
	  --output %D%/vcsn-tafkit-algos.cc.tmp                         \
		--header $(srcdir)/%D%/vcsn-tafkit.hh                   \
		vcsn/dyn/algos.json
	$(AM_V_at)for f in $(from_tafkit_gen);          \
	do                                              \
	  $(move_if_change) $$f.tmp $$f || exit 1;      \
	done
	$(AM_V_at)mv -f $@.tmp $@

$(from_tafkit_gen): %D%/tafkit.stamp
	@if test ! -f $@; then                  \
	  rm -f $<;                             \
	  $(MAKE) $(AM_MAKEFLAGS) $<;           \
	fi

pkglibexec_PROGRAMS = %D%/vcsn-tafkit
%C%_vcsn_tafkit_SOURCES = $(from_tafkit_gen) %D%/vcsn-tafkit.cc %D%/vcsn-tafkit.hh 
%C%_vcsn_tafkit_LDADD = $(all_libctx) $(libvcsn)
