#! /usr/bin/env python3

import sys
import argparse
from vcsn_tools.demangle import demangle

parser = argparse.ArgumentParser(
    description='''Demangle and prettify error output of the compiler''',
    epilog='''Install the `colorama` Python module to get colored output.''')
parser.add_argument('-c', '--color', dest='color', action='store',
                    default="auto",
                    choices=['auto', 'always', 'never'],
                    help='Whether to use colors in the output')

args = parser.parse_args()

for line in sys.stdin:
    print(demangle(line, color=args.color), end='')
    sys.stdout.flush()
