#! /usr/bin/env python3

from getpass import getuser
from datetime import datetime
from re import search

try:
    import psutil
    has_psutil = True
except ImportError:
    import warnings
    warnings.warn('you should install psutil for Python')
    import os
    has_psutil = False

from vcsn_tools.demangle import pretty_plugin


def memory(proc):
    res = proc.memory_info().rss
    for p in proc.children(recursive=True):
        res += p.memory_info().rss
    return res


def user_proc(proc):
    for elt in proc.cmdline():
        cmd = search(r'.*vcsn.compile.*\'.*?(/plugins/[^/]+/.*)\.cc\'.*$', elt)
        if cmd:
            title, message = pretty_plugin(cmd.group(1))
            delta = datetime.now() - datetime.fromtimestamp(proc.create_time())
            mem = memory(proc)
            print('{}:{:0>2}: {:.1f}GB: {:<10} {}'
                  .format(int(delta.seconds / 60),
                          delta.seconds % 60,
                          mem / 2 ** 30,
                          title + ':', message))

if has_psutil:
    for proc in psutil.process_iter():
        try:
            if proc.username() == getuser():
                user_proc(proc)
        except (psutil.AccessDenied, psutil.NoSuchProcess):
            pass
else:
    cmd = \
    r'''ps uxww |
        grep -v perl |
        grep "vcsn compile" |
        perl -ne "s{^.*'.*?/lib/plugins/(.*?)\.cc'.*$}{\$1}g && print \$_"'''
    os.system(cmd)
