digraph
{
  vcsn_context = "lal_char(abcdefghijk)_b"
  rankdir = LR
  {
    node [style = invis, shape = none, label = "", width = 0, height = 0]
    I0
    F10
  }
  {
    node [shape = circle]
    0
    1
    2
    3
    4
    5
    6
    7
    8
    9
    10
  }
  I0 -> 0
  0 -> 1 [label = "a, b, c, d, e, f, g, h, i, j, k"]
  1 -> 2 [label = "a, b, c, d, e, f, g, h, i, j, k"]
  2 -> 3 [label = "a, b, c, d, e, f, g, h, i, j, k"]
  3 -> 4 [label = "a, b, c, d, e, f, g, h, i, j, k"]
  4 -> 5 [label = "a, b, c, d, e, f, g, h, i, j, k"]
  5 -> 6 [label = "a, b, c, d, e, f, g, h, i, j, k"]
  6 -> 7 [label = "a, b, c, d, e, f, g, h, i, j, k"]
  7 -> 8 [label = "a, b, c, d, e, f, g, h, i, j, k"]
  8 -> 9 [label = "a, b, c, d, e, f, g, h, i, j, k"]
  9 -> 10 [label = "a, b, c, d, e, f, g, h, i, j, k"]
  10 -> F10
}
