#!/bin/bash -e

#set -x

export destinationdir="$(pwd)"
export sourcedir="$(pwd)/sources"
export scratchdir="$(pwd)/scratch"

# rm -rf "$scratchdir"/*
cp "$sourcedir"/*.{tex,bib} "$scratchdir"/
mkdir "$scratchdir" &> /dev/null || true
cd "$scratchdir"

for file in "$sourcedir"/notebooks/*.ipynb; do
    echo Converting "$file"...
    export title="$(basename "$(echo $file)" .ipynb \
        | sed 's/^[0-9]\+[- ]*//' | sed 's/_/\\_/g')"
    export goodfilename="$(basename "$(echo $file | tr [:blank:] '-' | tr _ '-')")"
    export goodbasename="$(basename "$goodfilename" .ipynb)"
    cp "$file" "$goodfilename" || true
    ipython nbconvert --to latex "$goodfilename" &> /dev/null

    export goodtexname="$goodbasename.tex"
    cp "$goodtexname" "$goodtexname.orig"
    export goodtextmpname="$goodbasename.tex.tmp"
    csplit -q "$goodtexname" '/^ *\\begin{document} *$/1'
    rm xx00
    echo "\\chapter{$title}" > "$goodtexname"
    cat xx01 \
        | sed 's/^\( \)*\\\(maketitle\|end{document}\)/% commented-out: \\\2/g' \
              >> "$goodtexname"
    rm xx01
done

echo "Compiling the big LaTeX file: pass 1..."

rm -f vaucanson-manual.idx
pdflatex vaucanson-manual < /dev/null &> /tmp/output || (cat /tmp/output ; exit -1)
echo "Compiling the big LaTeX file: BibTeX..."
bibtex vaucanson-manual < /dev/null
echo "Compiling the big LaTeX file: makeindex..."
touch vaucanson-manual.idx
makeindex vaucanson-manual
echo "Compiling the big LaTeX file: pass 2..."
pdflatex vaucanson-manual < /dev/null &> /tmp/output || (cat /tmp/output ; exit -1)
echo "Compiling the big LaTeX file: pass 3..."
pdflatex vaucanson-manual < /dev/null &> /tmp/output || (cat /tmp/output ; exit -1)

echo "Copying the compiled PDF file..."
cp "$scratchdir"/vaucanson-manual.pdf "$destinationdir"
