# -*- mode: ruby -*-

# Vagrantfile API/syntax version. Don't touch unless you know what
# you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "unstable64"
  config.vm.box_url = "unstable64.box"

  config.vm.hostname = "vcsn-bootstrap"

  # Port forwarding for VCSN Notebook.
  config.vm.network :forwarded_port, guest: 8888, host: 8890

  config.vm.provision "shell", path: "vcsn-bootstrap.sh"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "4069"]
    v.customize ["modifyvm", :id, "--cpus", "4"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end
end
